### ISSUE TITLE
Twitch Profile Request Fails with 410 Error

### ISSUE THREAD

**Issue by w3cj** [simov/grant-profile#12]
The twitch profile request currently fails with a 410 error. The request is missing the v5 accept header that is now required.

See the migration guide here: https://dev.twitch.tv/docs/v5/guides/migration#default-api-version

**Comment by simov** [comment]
Closed via https://github.com/simov/grant-profile/commit/51e68464d6be1cf742c26a103dcdd379dbb1c165
