### ISSUE TITLE
No support for custom providers

### ISSUE THREAD

**Issue by anbraten** [simov/grant-profile#7]
I am would like to use a custom provider with this package. 
Unlikely currently there is now way to pass the profile-url.

https://github.com/simov/grant-profile/blob/master/lib/client.js#L44

Maybe changing to something like this would already be working:

```
  url: provider.profileUrl || profile[provider.name].url
```

Maybe something similar for the before and after hooks could be useful as well.

**Comment by simov** [comment]
You're right, it's an oversight on my part. I'll do something about it.

**Comment by simov** [comment]
The additional `profile_url` landed in v0.0.5 :tada: 

Keep in mind that the internal HTTP client may still require additional logic for some of the providers.
